apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 5  # Number of replicas (pods)
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: flask-api:latest  # Replace with your Docker image name
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
